name: eslint

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  schedule:
    # Workflow runs every workday at 01:00 UTC
  - cron: '00 01 * * 1-5'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint with ESLint
        run: npx eslint .

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint and Generate SARIF Report
        run: npx eslint . --ext .js,.jsx,.ts,.tsx -f @microsoft/eslint-formatter-sarif -o results.sarif
      
      # available with GitHub Advanced Security | enterprise cloud, and enterprise server
      # - name: Upload SARIF Report
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: results.sarif